- packages/blend/__tests__/TESTING_GUIDE.md
- packages/blend/__tests__/components/Button/Button.performance.test.tsx
- packages/blend/__tests__/components/Button/README.md
- packages/blend/__tests__/components/Checkbox/Checkbox.accessibility.test.tsx
- packages/blend/__tests__/components/Checkbox/Checkbox.performance.test.tsx
- packages/blend/__tests__/components/Checkbox/Checkbox.test.tsx
- packages/blend/__tests__/components/Checkbox/README.md
- packages/blend/__tests__/components/Radio/README.md
- packages/blend/__tests__/components/Radio/Radio.accessibility.test.tsx
- packages/blend/__tests__/components/Radio/Radio.performance.test.tsx
- packages/blend/__tests__/components/Radio/Radio.test.tsx
- packages/blend/__tests__/components/Radio/RadioGroup.accessibility.test.tsx
- packages/blend/__tests__/components/Radio/RadioGroup.performance.test.tsx
- packages/blend/__tests__/components/Radio/RadioGroup.test.tsx
- packages/blend/__tests__/components/Switch/README.md
- packages/blend/__tests__/components/Switch/Switch.accessibility.test.tsx
- packages/blend/__tests__/components/Switch/Switch.performance.test.tsx
- packages/blend/__tests__/components/Switch/Switch.test.tsx
- packages/blend/__tests__/components/Switch/SwitchGroup.accessibility.test.tsx
- packages/blend/__tests__/components/Switch/SwitchGroup.performance.test.tsx
- packages/blend/__tests__/components/Switch/SwitchGroup.test.tsx
- packages/blend/__tests__/test-utils/builders.ts
- packages/blend/__tests__/test-utils/index.tsx
- packages/blend/__tests__/test-utils/performance.ts
- packages/blend/lib/components/Radio/Radio.tsx
- packages/blend/lib/components/Radio/RadioGroup.tsx
Added the unit test cases for the selector components 
---
run `pnpm test:blend` to see the results in terminal
run `pnpm test:blend:ui` to see the result in live ui
run `pnpm test:blend:coverage` to run the tests and store the report in `packages/blend/coverage/index.html`
---
Closes #122
> Ds 122 unit test cases selectors component

- .github/workflows/release.yml
- packages/blend/__tests__/test-utils/assertions.ts
Update the npm release workflow file  for beta support 
---
> fix: update npm release workflow

- .github/workflows/release.yml
> update version bump for npm 

- .github/workflows/release.yml
Add format check command in github workflow
> fix: add formatting step for generated files in release workflow

- .github/workflows/release.yml
- packages/blend/package.json
---
---
- ...
- ...
- ...
---
---
---
> Add debug steps for npm auth

- .github/workflows/release.yml
- packages/blend/.npmrc
---
---
- ...
- ...
- ...
---
---
---
> Add npmrc file

- .github/workflows/release.yml
> chore(release): allow stable release commits on main branch in CI

- .github/workflows/release.yml
> fix(release): handle existing tags before creating new ones

- .github/workflows/release.yml
- apps/site/src/demos/ChartsDemo.tsx
- apps/site/src/demos/SidebarDemo.tsx
- docs/CHANGELOG.md
- packages/blend/lib/breakpoints/breakPoints.ts
- packages/blend/lib/components/Charts/ChartHeader.tsx
- packages/blend/lib/components/Charts/ChartLegend.tsx
- packages/blend/lib/components/Charts/Charts.tsx
- packages/blend/lib/components/Charts/chart.tokens.ts
- packages/blend/lib/components/Charts/renderChart.tsx
- packages/blend/lib/components/Charts/types.tsx
- packages/blend/lib/context/ThemeContext.tsx
- packages/blend/lib/context/initComponentTokens.ts
- packages/blend/lib/context/useComponentToken.ts
- packages/blend/package.json
---
---
- ...
- ...
- ...
---
---
---
> Dev to Main

- .github/workflows/release.yml
---
---
- ...
- ...
- ...
---
---
---
> fix: minor fix

- apps/site/src/App.tsx
- apps/site/src/demos/ResponsiveSelectDemo.tsx
- apps/site/src/demos/SidebarDemo.tsx
- packages/blend/lib/components/Directory/NavItem.tsx
- packages/blend/lib/components/Directory/Section.tsx
- packages/blend/lib/components/Inputs/NumberInput/NumberInput.tsx
- packages/blend/lib/components/Sidebar/Sidebar.tsx
- packages/blend/lib/components/Sidebar/types.ts
- packages/blend/lib/components/SingleSelect/SingleSelect.tsx
- packages/blend/lib/components/SingleSelect/singleSelect.tokens.ts
- packages/blend/lib/components/SingleSelect/types.ts
Sidebar Styling and Prop fixes 
---
- Sidebar Styling and Prop fixes 
---
---
https://github.com/user-attachments/assets/1d474214-9bfc-47d1-908c-1bae7bc16a47
---
Closes #86 #85  #87
> 208 sidebar uistyling fix

- apps/site/src/demos/ChartsDemo.tsx
- packages/blend/lib/components/Charts/ChartHeader.tsx
- packages/blend/lib/components/Charts/ChartLegend.tsx
- packages/blend/lib/components/Charts/Charts.tsx
- packages/blend/lib/components/Charts/chart.tokens.ts
- packages/blend/lib/components/Charts/types.tsx
- packages/blend/lib/components/SingleSelect/SingleSelect.tsx
added collapse feature for charts
---
- added collapse feature for charts
---
---
https://github.com/user-attachments/assets/c4c5f189-c295-45ce-a7ea-dbb5554b0a3e
---
Closes  #223
> 223 expand and collapse functionality in the graph component

- apps/ascent/app/components/features/Documentation/Previews/StatCardPreview.tsx
- apps/site/src/demos/StatCardDemo.tsx
- packages/blend/lib/components/StatCard/StatCard.tsx
- packages/blend/lib/components/StatCard/types.ts
Changed the changeType "type" key to "valueType" 
---
---
- ...
- ...
- ...
---
---
---
Closes  #249
> fix: changed stats changeType key name from reserved to general

- apps/site/src/demos/DropdownInputDemo.tsx
- packages/blend/lib/components/Inputs/DropdownInput/DropdownInput.tsx
- packages/blend/lib/components/Inputs/DropdownInput/types.ts
- packages/blend/lib/components/Inputs/MultiValueInput/MultiValueInput.tsx
- packages/blend/lib/components/StatCard/StatCard.tsx
Added left dropdown position for dropdown input
added cross icon for multiValueInput 
---
---
- ...
- ...
- ...
---
---
---
Closes  #274 #253
> 272 multi select dropdown field not working for normal view but fine for mweb

- apps/storybook/stories/components/Alert/Alert.figma.tsx
- apps/storybook/stories/components/Avatar/Avatar.figma.tsx
- apps/storybook/stories/components/Avatar/AvatarGroup.figma.tsx
- apps/storybook/stories/components/Button/ButtonGroup.figma.tsx
- apps/storybook/stories/components/Modal/Modal.figma.tsx
- apps/storybook/stories/components/Sidebar/Sidebar.figma.tsx
- apps/storybook/stories/components/Tabs/Tabs.figma.tsx
- apps/storybook/stories/components/Tags/SplitTag.figma.tsx
---
---
- ...
- ...
- ...
---
---
---
> chore: added the correct mapping for some of the updated compomnents

- apps/site/src/demos/SidebarDemo.tsx
- packages/blend/lib/components/Select/SelectItem/index.tsx
- packages/blend/lib/components/Sidebar/Sidebar.tsx
- packages/blend/lib/components/Sidebar/types.ts
- add support any number of tenants to switch in the sidebar component
- show singleselect if we reach max tenant 
Closes #299
> feat: add maxVisibleItems prop to LeftPanelInfo

- apps/site/src/demos/MenuDemo.tsx
- packages/blend/lib/components/Menu/MenuItem.tsx
- packages/blend/lib/components/Menu/types.tsx
Added a tooltip support in the menu component with the same principles and construction as we have for single and multi select component 
Closes #344
> feat: added tooltip support in menu component

- apps/ascent/app/components/layout/SharedDocLayout.tsx
- apps/ascent/app/landing/components/footer/Footer.tsx
Added the hover state in the footer link of the landing page
Closes #380
> 380 hover state for footer links of landing page

- .husky/pre-commit
- apps/site/src/demos/SidebarDemo.tsx
- packages/blend/lib/components/Directory/NavItem.tsx
- packages/blend/lib/components/Menu/Menu.tsx
- packages/blend/lib/components/Sidebar/Sidebar.tsx
- packages/blend/lib/components/Sidebar/SidebarFooter.tsx
- packages/blend/lib/components/Sidebar/SidebarHeader.tsx
- packages/blend/lib/components/Sidebar/TenantPanel.tsx
- packages/blend/lib/components/Sidebar/types.ts
- packages/blend/lib/components/Sidebar/utils.ts
- packages/blend/lib/components/SingleSelect/SingleSelectMenu.tsx
- packages/blend/lib/components/Topbar/Topbar.tsx
- packages/blend/lib/components/Topbar/topbar.tokens.ts
Update sidebar  according to the comments
Closes #400
> feat: add TenantItem type and SidebarFooter enhance tenant arrangement

- packages/blend/lib/components/DateRangePicker/DateRangePicker.tsx
- packages/blend/lib/components/DateRangePicker/QuickRangeSelector.tsx
- packages/blend/lib/components/KeyValuePair/KeyValuePair.tokens.ts
- packages/blend/lib/components/KeyValuePair/KeyValuePair.tsx
> Update key value pair component

- packages/blend/lib/components/DateRangePicker/QuickRangeSelector.tsx
> dev to staging build fix

- apps/site/src/demos/ChartsDemo.tsx
- packages/blend/lib/components/Charts/ChartUtils.tsx
- packages/blend/lib/components/Charts/CustomTooltip.tsx
- packages/blend/lib/components/Charts/types.tsx
Removed year from the Date time support, fixed smart formatting
> fix: fixed charts ticks issue

- apps/site/src/demos/DrawerDemo.tsx
- packages/blend/lib/components/DataTable/ColumnManager.tsx
- packages/blend/lib/components/DataTable/DataTable.tsx
- packages/blend/lib/components/DataTable/TableBody/index.tsx
- packages/blend/lib/components/DataTable/TableCell/index.tsx
- packages/blend/lib/components/DataTable/TableHeader/index.tsx
- packages/blend/lib/components/DataTable/TableHeader/types.ts
- packages/blend/lib/components/DataTable/types.ts
- packages/blend/lib/components/DateRangePicker/DateRangePicker.tsx
- packages/blend/lib/components/DateRangePicker/QuickRangeSelector.tsx
- packages/blend/lib/components/DateRangePicker/types.ts
- packages/blend/lib/components/Directory/NavItem.tsx
- packages/blend/lib/components/Drawer/components/DrawerBase.tsx
- packages/blend/lib/components/Drawer/drawer.tokens.ts
- packages/blend/lib/components/Menu/Menu.tsx
- packages/blend/lib/components/Menu/menu.styles.ts
- packages/blend/lib/components/MultiSelect/MultiSelectMenu.tsx
- packages/blend/lib/components/MultiSelect/MultiSelectSubMenu.tsx
- packages/blend/lib/components/Sidebar/TenantPanel.tsx
- packages/blend/lib/components/SingleSelect/SingleSelectMenu.tsx
- packages/blend/lib/components/Tooltip/Tooltip.tsx
Update 
- data table
- calendar fixed
- drawer z-index
- sidebar fixed
Closes #424
> Update data table , calendar,  drawer, sidebar

- apps/site/src/demos/DateRangePickerDemo.tsx
- apps/storybook/stories/components/DateRangePicker/DateRangePicker.stories.tsx
- packages/blend/lib/components/DateRangePicker/DateRangePicker.tsx
- packages/blend/lib/components/DateRangePicker/constants.ts
- packages/blend/lib/components/DateRangePicker/types.ts
- packages/blend/lib/components/DateRangePicker/utils.ts
> Enhance preset detection and add yesterday range example

- apps/site/src/demos/StatCardDemo.tsx
- packages/blend/lib/components/Popover/Popover.tsx
- packages/blend/lib/components/StatCard/StatCard.tsx
- packages/blend/lib/components/Tabs/TabsList.tsx
1. Fixed popover width issue
2. Added truncation in title for statCard
3. Added autScrollng in TabList
> Bug fix/data display

- apps/site/src/demos/DateRangePickerDemo.tsx
- packages/blend/lib/components/DateRangePicker/CalendarGrid.tsx
- packages/blend/lib/components/DateRangePicker/DateRangePicker.tsx
- packages/blend/lib/components/DateRangePicker/QuickRangeSelector.tsx
- packages/blend/lib/components/DateRangePicker/types.ts
- packages/blend/lib/components/DateRangePicker/utils.ts
- packages/blend/lib/components/Tabs/StyledTabs.tsx
- packages/blend/lib/components/Tabs/TabsList.tsx
- fix calendar scroll and give custom preset option
- add border bottom for underline variant
> Fix tabs and calendar

- apps/site/src/demos/DateRangePickerDemo.tsx
- apps/site/src/demos/MenuDemo.tsx
- packages/blend/lib/components/Menu/Menu.tsx
- packages/blend/lib/components/Menu/types.tsx
- packages/blend/lib/components/VirtualList/VirtualList.tsx
- packages/blend/lib/components/VirtualList/index.ts
- packages/blend/lib/components/VirtualList/types.ts
- packages/blend/lib/components/VirtualList/utils.ts
- packages/blend/lib/main.ts
Create a virtual list 
Closes #454
> feat: add VirtualList component for efficient rendering of large lists

- packages/blend/lib/components/DateRangePicker/utils.ts
Add "This Month" and "Last Month" preset matching in daterangepicker
> feat: add "This Month" and "Last Month" preset matching 
